[build]
builder = "DOCKERFILE"
buildCommand = "python main.py"
dockerfilePath = "=Dockerfile.origin"

[deploy]
startCommand = "yarn run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
